import Head from 'next/head';
import CrewMember from '../components/Crew';
import Navbar from '../components/Shared/Navbar';

export default function Crew() {
	return (
		<>
			<Head>
				<title>Destination | Space Tourism</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-screen h-screen bg-crew-desktop  tablet:bg-crew-tablet mobile:bg-crew-mobile bg-no-repeat bg-cover select-none bg-fixed mobile:h-auto">
				<Navbar />
				<div className="flex flex-col items-center justify-between tablet:flex-col mt-[50px] px-[200px] tablet:px-[0px] tablet:mt-[100px] mobile:mt-[40px]">
					<div className="font-barlowCondensed text-[28px] tablet:text-[20px] tracking-[4.72px] self-start tablet:px-[50px] mobile:text-[16px] mobile:self-center">
						<span className="text-white/[0.5] font-bold pr-5">
							02
						</span>
						<span className="text-white">MEET YOUR CREW</span>
					</div>
					<CrewMember />
				</div>
			</div>
		</>
	);
}
