import type { NextPage } from 'next';
import Head from 'next/head';

import Home from '../components/Home';

const MainPage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Space Tourism</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Home />
		</div>
	);
};

export default MainPage;
