import Head from 'next/head';
import { useState } from 'react';
import Navbar from '../components/Shared/Navbar';
import TechnologyComponent from '../components/Technology';
import { ITechnology } from '../types/interfaces';

enum technologyMenuChoice {
	LAUNCH_VEHICLE = 'LAUNCH VEHICLE',
	SPACEPORT = 'SPACEPORT',
	SPACE_CAPSULE = 'SPACE CAPSULE',
}

export default function Technology() {
	const [technologyData, setTechnologyData] = useState<ITechnology>(
		technologyDataArray[2]
	);

	const [menuChoice, setMenuChoice] = useState<technologyMenuChoice>(
		technologyMenuChoice.LAUNCH_VEHICLE
	);

	const setTechnologyDataChoice = (choice: technologyMenuChoice) => {
		setTechnologyData(
			technologyDataArray.filter((data: ITechnology) =>
				data.title.includes(choice)
			)[0]
		);
		setMenuChoice(choice);
	};

	return (
		<>
			<Head>
				<title>Technology | Space Tourism</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="w-screen grid h-screen mobile:min-h-screen place-items-start content-start mobile:place-items-center bg-technology-desktop tablet:bg-technology-tablet mobile:bg-technology-mobile bg-no-repeat bg-cover select-none bg-fixed mobile:h-auto ">
				<Navbar />
				<div className="font-barlowCondensed self-start pl-[200px] text-[28px] my-[50px] tablet:text-[20px] mobile:my-[20px] tracking-[4.72px] tablet:px-[50px] mobile:text-[16px] mobile:self-center">
					<span className="text-white/[0.5] font-bold pr-5">03</span>
					<span className="text-white">SPACE LAUNCH 101</span>
				</div>
				<div className="grid self-start h-auto overflow-hidden tablet:place-items-center">
					<TechnologyComponent
						{...technologyData}
						setTechnologyDataChoice={setTechnologyDataChoice}
						technologyChoice={menuChoice}
					/>
				</div>
			</div>
		</>
	);
}

const technologyDataArray: ITechnology[] = [
	{
		title: 'LAUNCH VEHICLE',
		description:
			"A launch vehicle or carrier rocket is a rocket-propelled vehicle used to carry a payload from Earth's surface to space, usually to Earth orbit or beyond. Our WEB-X carrier rocket is the most powerful in operation. Standing 150 metres tall, it's quite an awe-inspiring sight on the launch pad!",
		imageURL: '/assets/technology/image-launch-vehicle-portrait.jpg',
	},
	{
		title: 'SPACEPORT',
		description:
			'A spaceport or cosmodrome is a site for launching (or receiving) spacecraft, by analogy to the seaport for ships or airport for aircraft. Based in the famous Cape Canaveral, our spaceport is ideally situated to take advantage of the Earth’s rotation for launch.',
		imageURL: '/assets/technology/image-spaceport-portrait.jpg',
	},
	{
		title: 'SPACE CAPSULE',
		description:
			"A space capsule is an often-crewed spacecraft that uses a blunt-body reentry capsule to reenter the Earth's atmosphere without wings. Our capsule is where you'll spend your time during the flight. It includes a space gym, cinema, and plenty of other activities to keep you entertained.",
		imageURL: '/assets/technology/image-space-capsule-portrait.jpg',
	},
];
